version: '3.8'

services:
  primary:
    image: postgres:15
    container_name: pg_primary
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
    volumes:
      - pg_primary_data:/var/lib/postgresql/data
      - ./primary/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - pg_net

  replica1:
    image: postgres:15
    container_name: pg_replica1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - primary
    volumes:
      - pg_replica1_data:/var/lib/postgresql/data
      - ./replica/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    networks:
      - pg_net

  replica2:
    image: postgres:15
    container_name: pg_replica2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - primary
    volumes:
      - pg_replica2_data:/var/lib/postgresql/data
      - ./replica/init:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"
    networks:
      - pg_net

volumes:
  pg_primary_data:
  pg_replica1_data:
  pg_replica2_data:

networks:
  pg_net:
